# Generated by Django 5.0.6 on 2024-06-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, null=True)),
                ('cracha', models.CharField(max_length=50, null=True)),
                ('senha', models.CharField(max_length=128, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('cargo', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
