# Generated by Django 5.0.7 on 2024-07-21 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('badge', models.IntegerField(null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('ranking', models.CharField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Operator',
                'verbose_name_plural': 'Operators',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_called', models.IntegerField()),
                ('information', models.CharField(max_length=255, null=True)),
                ('order_quantity', models.PositiveIntegerField(null=True)),
                ('branch', models.CharField(choices=[('Matriz (01)', 'Matriz (01)'), ('Parobé (04)', 'Parobé (04)'), ('Campo Bom (11)', 'Campo Bom (11)'), ('Dois Irmãos (03 - 05)', 'Dois Irmãos (03 - 05)'), ('São Paulo (02)', 'São Paulo (02)')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('patrimony', models.CharField(blank=True, max_length=6, null=True)),
                ('maq', models.IntegerField(blank=True, null=True)),
                ('movimentation', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('patrimony', models.CharField(blank=True, max_length=6, null=True)),
                ('maq', models.IntegerField(blank=True, null=True)),
                ('retreat_date', models.DateField(verbose_name='Data de Retirada')),
                ('devolution_date', models.DateField(verbose_name='Data de Devolução')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.equipment')),
            ],
        ),
    ]
