# Generated by Django 5.0.6 on 2024-06-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_admin2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin2',
        ),
    ]
