# Generated by Django 5.0.7 on 2024-07-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_order_operator_staff_alter_loan_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='ranking',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
