# Generated by Django 5.0.6 on 2024-06-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_admin2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterField(
            model_name='admin',
            name='cracha',
            field=models.IntegerField(null=True),
        ),
    ]
