# Generated by Django 5.0.6 on 2024-07-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_admin_options_alter_admin_cracha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specification', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('Periféricos', 'Periféricos'), ('Notebook', 'Notebook'), ('Cabos', 'Cabos')], max_length=50)),
                ('patrimony', models.IntegerField(blank=True)),
                ('maq', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='cracha',
            new_name='badge',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='senha',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='cargo',
            new_name='ranking',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='usuario',
            new_name='username',
        ),
    ]
