# Generated by Django 5.0.7 on 2024-07-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_staff_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='patrimony',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='num_called',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='patrimony',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
