# Generated by Django 5.0.6 on 2024-07-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_equipment_rename_cracha_admin_badge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='maq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='patrimony',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
