# Generated by Django 5.0.7 on 2024-07-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_loan_patrimony_alter_order_num_called_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='information',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
