# Generated by Django 5.0.7 on 2024-07-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_order_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='num_called',
            field=models.IntegerField(),
        ),
    ]
