# Generated by Django 5.0.6 on 2024-07-05 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_equipment_quantity_alter_equipment_maq_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Operator',
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Operator', 'verbose_name_plural': 'Operators'},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='maq',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='patrimony',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='specification',
        ),
        migrations.AddField(
            model_name='order',
            name='maq',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='movimentation',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], default='Saída', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.operator'),
        ),
        migrations.AddField(
            model_name='order',
            name='patrimony',
            field=models.CharField(default='SEM PATRIMÔNIO', max_length=6, null=True),
        ),
    ]
