# Generated by Django 5.0.7 on 2024-07-26 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_order_order_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Item',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='name',
        ),
        migrations.AddField(
            model_name='equipment',
            name='cost_center',
            field=models.IntegerField(blank=True, null=True, verbose_name='Centro de Custo'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='express_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Express Code'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='immobilized',
            field=models.IntegerField(blank=True, null=True, verbose_name='Imobilizado'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='Informações'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.item'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='maq',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maq'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='nf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NF'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='nf_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data NF'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='patrimony',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Patrimônio'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.sector'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='sn_pn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='S/N - P/N'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fornecedor'),
        ),
    ]
