# Generated by Django 5.0.6 on 2024-07-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_admin_operator_alter_operator_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='maq',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='patrimony',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
