# Generated by Django 5.0.6 on 2024-07-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_order_maq_alter_order_patrimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='maq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='patrimony',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
