# Generated by Django 5.0.6 on 2024-07-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_order_maq_alter_order_patrimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sector',
            field=models.CharField(choices=[('TI', 'TI'), ('Marketing', 'Marketing'), ('Almox', 'Almox')], default='TI', max_length=50),
            preserve_default=False,
        ),
    ]
