# Generated by Django 5.0.7 on 2024-07-26 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_equipment_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.sector'),
        ),
    ]
