# Generated by Django 5.0.6 on 2024-07-08 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_order_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.CharField(choices=[('Matriz (01)', 'Matriz (01)'), ('Parobé (04)', 'Parobé (04)'), ('Campo Bom (11)', 'Campo Bom (11)'), ('Dois Irmãos (03 - 05)', 'Dois Irmãos (03 - 05)'), ('São Paulo (02)', 'São Paulo (02)')], default='Matriz (01)', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sector'),
        ),
    ]
