# Generated by Django 5.0.7 on 2024-08-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_equipment_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='movimentation',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1),
        ),
    ]
