# Generated by Django 5.0.6 on 2024-07-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_category_sector_order_branch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='order',
            name='information',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
