# Generated by Django 5.0.7 on 2024-08-19 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_order_movimentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.staff'),
        ),
    ]
