# Generated by Django 5.0.7 on 2024-08-19 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_equipment_current_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='current_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_equipment', to='dashboard.staff'),
        ),
    ]
