# Generated by Django 5.0.6 on 2024-07-12 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_category_options_order_information'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('patrimony', models.CharField(blank=True, max_length=6, null=True)),
                ('maq', models.IntegerField(blank=True, null=True)),
                ('retreat_date', models.DateTimeField(auto_now_add=True)),
                ('devolution_date', models.DateField(verbose_name='Data de Devolução')),
                ('equipment', models.ManyToManyField(to='dashboard.equipment')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
