# Generated by Django 5.0.7 on 2024-08-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_equipment_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
