# Generated by Django 5.0.6 on 2024-07-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='retreat_date',
            field=models.DateField(verbose_name='Data de Retirada'),
        ),
    ]
