# Generated by Django 5.0.6 on 2024-07-12 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_loan_retreat_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='equipment',
        ),
        migrations.AddField(
            model_name='loan',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.equipment'),
        ),
    ]
