# Generated by Django 5.0.6 on 2024-07-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_loan_equipment_loan_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='badge',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='ranking',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
