# Generated by Django 5.0.7 on 2024-09-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
