# Generated by Django 5.0.7 on 2024-10-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_loan_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='views',
        ),
        migrations.RemoveField(
            model_name='order',
            name='views',
        ),
    ]
