# Generated by Django 5.0.7 on 2024-12-06 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_loan_views_remove_order_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='equipment',
        ),
        migrations.AddField(
            model_name='loan',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.item'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
