# Generated by Django 5.0.7 on 2024-12-06 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_loan_equipment_loan_item_alter_loan_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.equipment'),
        ),
    ]
