# Generated by Django 5.0.7 on 2024-12-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_loan_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='equipment',
        ),
    ]
