# Generated by Django 5.0.7 on 2024-12-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_loan_current_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='current_user',
            new_name='user_current',
        ),
    ]
