# Generated by Django 5.0.7 on 2024-12-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_rename_current_user_loan_user_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='user_current',
        ),
    ]
