# Generated by Django 5.0.7 on 2024-12-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_remove_loan_user_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
