# Generated by Django 5.0.7 on 2024-12-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_loan_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
