# Generated by Django 5.0.6 on 2024-07-21 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_operator_badge_alter_operator_ranking'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_badge', to='dashboard.operator', to_field='badge'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ranking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_ranking', to='dashboard.operator', to_field='ranking'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sector'),
        ),
    ]
