# Generated by Django 5.0.6 on 2024-07-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_badge_profile_ranking_alter_profile_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='badge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ranking',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
