# Generated by Django 5.0.7 on 2024-07-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badge',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
